complete -c db -f -n __fish_is_first_token -a postgres -d "PostgreSQL database"
complete -c db -f -n __fish_is_first_token -a pg -d "PostgreSQL (alias)"
complete -c db -f -n __fish_is_first_token -a mariadb -d "MariaDB database"
complete -c db -f -n __fish_is_first_token -a maria -d "MariaDB (alias)"
complete -c db -f -n __fish_is_first_token -a mongodb -d "MongoDB database"
complete -c db -f -n __fish_is_first_token -a mongo -d "MongoDB (alias)"
complete -c db -f -n __fish_is_first_token -a mysql -d "MySQL database"
complete -c db -f -n __fish_is_first_token -a "help -h --help" -d "Show usage information"
